# Generated by Django 4.2.3 on 2025-08-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_submission_question_choice_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='anonymous', max_length=100)),
                ('image', models.ImageField(upload_to='developer_images/')),
                ('role', models.CharField(max_length=500)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
    ]
