# Generated by Django 4.2.3 on 2025-08-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='Anonymous', max_length=100)),
                ('image', models.ImageField(upload_to='team_images/')),
                ('role', models.CharField(max_length=500)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('description', models.TextField(blank=True, max_length=5000)),
            ],
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
    ]
