# Generated by Django 4.2.3 on 2025-08-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_team_delete_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=100)),
                ('image', models.ImageField(upload_to='news_images/')),
                ('pub_date', models.DateField(null=True)),
                ('mod_date', models.DateField(null=True)),
                ('keyword', models.TextField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, max_length=5000)),
            ],
        ),
    ]
