# Generated by Django 4.2.3 on 2025-08-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='news',
            name='keyword',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
