# Generated by Django 4.2.3 on 2025-08-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0006_alter_news_description_alter_news_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.CharField(default='URL', max_length=500, null=True),
        ),
    ]
