# Generated by Django 4.2.3 on 2025-08-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0007_news_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='contact',
            field=models.CharField(default='Contact', max_length=100),
        ),
    ]
