# Generated by Django 4.2.3 on 2025-08-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0011_reaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='type',
            new_name='reaction_type',
        ),
    ]
