# Generated by Django 4.2.3 on 2025-08-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0012_rename_type_reaction_reaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='description',
            new_name='text',
        ),
    ]
