# Generated by Django 4.2.3 on 2025-08-07 22:18

from django.db import migrations, models
import onlinecourse.models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0013_rename_description_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=onlinecourse.models.upload_to_course_images),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=onlinecourse.models.upload_to_news_images),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=onlinecourse.models.upload_to_team_images),
        ),
    ]
