# Generated by Django 4.2.3 on 2025-08-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0014_alter_course_image_alter_news_image_alter_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
