# Generated by Django 4.2.3 on 2025-08-08 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlinecourse', '0015_alter_news_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='team',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='team',
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_amount', models.CharField(choices=[('rating_1', 'rating_1'), ('rating_2', 'rating_2'), ('rating_3', 'rating_3'), ('rating_4', 'rating_4'), ('rating_5', 'rating_5')], max_length=10)),
                ('rated_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.course')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
