# Generated by Django 4.2.3 on 2025-08-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0016_remove_comment_team_remove_reaction_team_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_amount',
            field=models.CharField(choices=[('rating_1', 'rating_1'), ('rating_2', 'rating_2'), ('rating_3', 'rating_3'), ('rating_4', 'rating_4'), ('rating_5', 'rating_5'), ('rating_avg', 'rating_avg')], max_length=10),
        ),
    ]
