# Generated by Django 4.2.3 on 2025-08-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0017_alter_rating_rating_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_amount',
            field=models.CharField(choices=[('rating_1', 'rating_1'), ('rating_2', 'rating_2'), ('rating_3', 'rating_3'), ('rating_4', 'rating_4'), ('rating_5', 'rating_5')], max_length=10),
        ),
    ]
